steps:
  - name: "gcr.io/cloud-builders/gcloud" # cloud builder with gcloud installed
    id: Update live server
    entrypoint: /bin/sh
    args: ['gcloud', 'compute', 'ssh', 'eisandbar@website', '--zone=us-east4-c', '--command='/bins/sh /home/eisandbar/website/pull.sh'']
