version: '3'

services:
  nginx:
    container_name: eisandbar-nginx
    build: 
      context: ./nginx/
      dockerfile: Dockerfile
    ports: 
      - "127.0.0.1:3000:80"
    restart: on-failure
    volumes:
      - ./build:/var/www/eisandbar/html

  website:
    container_name: website
    build: 
      context: ./website/
      dockerfile: Dockerfile
    volumes:
      - ./build/:/website/dist/
