version: '3'

services:
  nginx:
    container_name: nginx
    build: 
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 443:443
      - 80:80
    restart: on-failure
    volumes:
      - ./build:/var/www/eisandbar/html

  website:
    container_name: website
    build: 
      context: ./website/
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./build/:/website/dist/